// @flow
export const STORE_ENTITIES = 'STORE_ENTITIES'
export const STORE_ENTITIY = 'STORE_ENTITIY'
export const STORE_NEW_ENTITY = 'STORE_NEW_ENTITY'
export const REMOVE_ENTITY = 'REMOVE_ENTITY'
export const REMOVE_ENTITY_DATA = 'REMOVE_ENTITY_DATA'
export const STORE_ENTITY_DATA = 'STORE_ENTITY_DATA'
