// @flow
export const STORE_ENTITIES = 'STORE_ENTITIES'
export const STORE_ENTITIY = 'STORE_ENTITIY'
export const STORE_NEW_ENTITY = 'STORE_NEW_ENTITY'
export const DELETE_ENTITY = 'DELETE_ENTITY'
export const DELETE_ENTITY_DATA = 'DELETE_ENTITY_DATA'
export const STORE_ENTITY_DATA = 'STORE_ENTITY_DATA'
